name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile-cracking-library:
    name: Compile cracking library
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Download Z3 (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/main/c
        run: |
          wget --no-verbose https://github.com/Z3Prover/z3/releases/download/z3-4.15.4/z3-4.15.4-x64-glibc-2.39.zip
          unzip z3-4.15.4-x64-glibc-2.39.zip
          mv z3-4.15.4-x64-glibc-2.39 z3
          cp z3/bin/libz3.so ../resources

      - name: Download Z3 (macos-latest)
        if: matrix.os == 'macos-latest'
        working-directory: src/main/c
        run: |
          wget --no-verbose https://github.com/Z3Prover/z3/releases/download/z3-4.15.4/z3-4.15.4-arm64-osx-13.7.6.zip
          wget --no-verbose https://github.com/Z3Prover/z3/releases/download/z3-4.15.4/z3-4.15.4-x64-osx-13.7.6.zip
          unzip z3-4.15.4-arm64-osx-13.7.6.zip
          unzip z3-4.15.4-x64-osx-13.7.6.zip
          mv z3-4.15.4-x64-osx-13.7.6 z3
          lipo -create -output z3/bin/libz3.dylib z3-4.15.4-arm64-osx-13.7.6/bin/libz3.dylib z3/bin/libz3.dylib
          cp z3/bin/libz3.dylib ../resources

      - name: Download Z3 (windows-latest)
        if: matrix.os == 'windows-latest'
        working-directory: src/main/c
        run: |
          Invoke-WebRequest -OutFile "z3-4.15.4-x64-win.zip" https://github.com/Z3Prover/z3/releases/download/z3-4.15.4/z3-4.15.4-x64-win.zip
          tar -xf z3-4.15.4-x64-win.zip
          mv z3-4.15.4-x64-win z3
          mv z3/bin/libz3.dll ../resources

      - name: Build cracking library (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/main/c
        run: |
          g++ -shared -o libcrack.so blocks.cpp xsinv.cpp java_helper.cpp -std=c++23 -O3 -fopenmp -fPIC -static-libgcc -static-libstdc++ -Iz3/include -Lz3/bin -lz3 -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux"
          cp libcrack.so ../resources

      - name: Build cracking library (macos-latest)
        if: matrix.os == 'macos-latest'
        working-directory: src/main/c
        run: |
          g++-15 -dynamiclib -o libcrack.dylib blocks.cpp xsinv.cpp java_helper.cpp -std=c++23 -O3 -fopenmp -fPIC -arch arm64 -arch x86_64 -static-libgcc -static-libstdc++ -Iz3/include -Lz3/bin -lz3 -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/darwin"
          cp libcrack.dylib ../resources

      - name: Build cracking library (windows-latest)
        if: matrix.os == 'windows-latest'
        working-directory: src/main/c
        run: |
          g++ -shared -o crack.dll blocks.cpp xsinv.cpp java_helper.cpp -std=c++23 -O3 -fopenmp -static-libgcc -static-libstdc++ -Iz3/include -Lz3/bin -lz3 -I"$env:JAVA_HOME/include" -I"$env:JAVA_HOME/include/win32"
          cp crack.dll ../resources

      - name: Capture shared libraries (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Shared libraries (ubuntu-latest)
          path: |
            src/main/resources/libz3.so
            src/main/resources/libcrack.so
      - name: Capture shared libraries (macos-latest)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Shared libraries (macos-latest)
          path: |
            src/main/resources/libz3.dylib
            src/main/resources/libcrack.dylib
      - name: Capture shared libraries (windows-latest)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Shared libraries (windows-latest)
          path: |
            src/main/resources/libz3.dll
            src/main/resources/crack.dll

  build:
    name: Build mod
    needs: compile-cracking-library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Capture shared library
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: src/main/resources/
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BedrockSeed
          path: build/libs/
